### ISSUE TITLE
clang-cl.exe : error : no such file or directory: '/permissive-'

### ISSUE THREAD

**Issue by kasru** [arves100/llvm-vs2017-integration#5]
- Setup clang 6.0 for Windows
- Replase "5.0" to "6.0.0" in file

Compile error: 
clang-cl.exe : error : no such file or directory: '/permissive-'

**Comment by arves100** [comment]
This files were tested for clang 5.0, I wil look for clang 6

**Comment by CuteLasty** [comment]
That is visual studio 2017 option.
You can set project property / C/C++ / Language / Conformance mode to "No" to disable it.

**Comment by KeyC0de** [comment]
Unfortunately the error persists: `no such file or directory: '/JMC'`

**Comment by PaTiToMaSteR** [comment]
Because /JMC is the new feature of VS2017, which you can deactivate in C/C++ section, writing in the search box "/JMC", and assign it to No.

Hope this helps!

**Comment by arves100** [comment]
Should I keep this issue open, or the permissive error is fixed?

**Comment by PaTiToMaSteR** [comment]
As far I try still an issue, unless there is a new version that worked the problem🤔

**Comment by arves100** [comment]
Uhmmm you could try with the last version and tell me clang+vs version so I
can try reproduce the issue.

Il giorno lun 31 dic 2018, 11:23 PaTiTo MaSteR <notifications@github.com>
ha scritto:

> As far I try still an issue, unless there is a new version that worked the
> problem🤔
>
>
